name: pp_442
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_toggle_switch: ^0.8.3
  auto_route: ^8.2.0
  bloc: ^8.1.4
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  easy_date_timeline: ^1.1.3
  fl_chart: ^0.69.0
  flagsmith: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.3
  flutter_native_splash: ^2.4.1
  flutter_shake_animated: ^0.0.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.9
  intl: ^0.19.0
  is_first_run: ^1.0.0
  package_info_plus: ^8.0.0
  pull_down_button: ^0.10.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  freezed: ^2.5.2
  flutter_gen_runner:
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/appbar/
    - assets/images/categories/
    - assets/images/onboarding/
    - assets/images/placeholders/

flutter_native_splash:
  image: assets/icon.png
  color: "#4E2FA9"
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
